---
apiVersion: v1
kind: Service
metadata:
  name: devops-community
  namespace: devops-community
spec:
  selector:
    app.kubernetes.io/name: devops-community
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
