name: golang-pipeline
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build and push
      id: gen_tags
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["user/image:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      # needs: gen_tags
      with:
        context: .
        push: true
        tags: ${{ steps.gen_tags.outputs.tags }}
